export const pageLayout = {
  shell: 'mx-auto w-full max-w-[var(--layout-wide-max)]',
  content: 'mx-auto w-full max-w-[var(--layout-content-max)]',
  reading: 'mx-auto w-full max-w-[var(--layout-reading-max)]',
  appCanvas: 'mx-auto w-full max-w-[var(--layout-app-max)]',
  pageGutter: 'px-4 md:px-8 xl:px-10',
  pageCanvas: 'mx-auto w-full max-w-[var(--layout-app-max)] px-4 md:px-8 xl:px-10',
  pageFlow: 'space-y-10 pb-16 md:space-y-14',
  compactFlow: 'space-y-8 md:space-y-10',
  sectionFlow: 'space-y-5 md:space-y-7',
  sectionDivider: 'border-t border-border pt-8 md:pt-12',
  sectionHeader: 'ui-section-header gap-4',
  sectionIntro: 'ui-section-intro',
  actionRow: 'ui-action-row',
  actionRowEnd: 'ui-action-row-end',
  controlStack: 'ui-control-stack',
  resultPanel: 'ui-result-panel',
  calculatorGrid:
    'grid grid-cols-1 gap-8 xl:grid-cols-[420px_minmax(0,1fr)] xl:items-start xl:gap-10',
  stickyScenario: 'space-y-5 xl:sticky xl:top-8 xl:h-fit',
  stickySidebar: 'space-y-5 lg:sticky lg:top-8 lg:h-fit',
  compactCalculatorGrid:
    'grid grid-cols-1 gap-6 lg:grid-cols-[minmax(18rem,0.7fr)_minmax(0,1.3fr)] lg:items-start lg:gap-8',
  equalCalculatorGrid: 'grid grid-cols-1 gap-6 xl:grid-cols-2 xl:items-start xl:gap-8',
  reportGrid: 'grid grid-cols-1 gap-6 xl:grid-cols-[minmax(0,1fr)_20rem] xl:items-start',
  metricGridTwo: 'grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-5',
  metricGridThree: 'grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3 md:gap-5',
  metricGridFour: 'grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4 md:gap-5',
  mobileActionSpace: 'pb-20 lg:pb-0',
  mobileActionBar: 'ui-mobile-action-bar',
  mobileActionBarInner: 'ui-mobile-action-bar-inner',
  resultFlow: 'space-y-8 md:space-y-10',
} as const;

export const pageSurface = {
  plain: 'bg-transparent',
  panel: 'ui-surface',
  inset: 'ui-surface-inset',
  flush: 'ui-surface-flush',
  raised: 'ui-surface-raised',
} as const;

export const pageCopy = {
  title: 'ui-page-title',
  sectionTitle: 'ui-section-title',
  cardTitle: 'ui-card-title',
  body: 'ui-body',
  meta: 'ui-meta',
  eyebrow: 'ui-eyebrow',
  caption: 'ui-caption',
  label: 'ui-label',
  description: 'ui-field-description',
  metric: 'ui-primary-metric financial-number',
  largeMetric: 'ui-large-metric financial-number',
} as const;
